### ISSUE TITLE
React to deceased ssn when running against the national registry

### ISSUE THREAD

**Issue by bjornlevi** [piratar/icepirate#4]
Deceased people should be removed from the member registry.

**Comment by BjarniRunar** [comment]
Yes. Awkward question, but do you have an example of a kennitala I could test against, to see what the data from our providers looks like? A private message would probably be appropriate...

**Comment by helgihg** [comment]
This won't be implemented in an automatic fashion. We will only be looking up people in the registry upon request, such as when a user logs into the voting system (Wasa2il) or performs some other action requiring a look-up. In order to look up deceased individuals we would need to periodically look up the entire member database which is expensive, being paid per lookup. We might possibly justify incurring this cost once a year (at the absolute most), or once every few years, but even then, it doesn't make sense to implement this in some automatic fashion considering how many other much more important things need attention before that... for example implementing a new lookup mechanism in the first place.
